# Generated by Django 4.1.6 on 2023-02-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_group_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
    ]
