# Generated by Django 4.1.6 on 2023-02-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_teacher_name_teacher_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('subject', models.CharField(choices=[('INF', 'Informatics'), ('ENG', 'English'), ('PHYS', 'Physics')], default='INF', max_length=20)),
            ],
        ),
    ]
